### ISSUE TITLE
Took out async functions?

### ISSUE THREAD

**Issue by u382514** [googleads/googleads-shopping-samples#6]
Just wondering why the async functions were taken out of the sample.

**Comment by yufengg** [comment]
We updated the batching examples to use the custombatch method rather than using native batching. https://developers.google.com/shopping-content/v2/reference/v2/products/custombatch

Regarding the implementation of async functions, the main benefit of having them was to stream the response piece back, but the service returning it all at once anyway, so that benefit was not present. You are more than welcome to use async for a myriad of other reasons but since it's not part of the API and also not a use case that we are trying to showcase, it was removed.

**Comment by u382514** [comment]
Thank you very much for the clarification!
